apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ai-react
  namespace: default
  annotations:
    # 여기서 Image Updater가 모니터링할 이미지와 전략 지정
    argocd-image-updater.argoproj.io/image-list: lkh8150/k8s-ai-react
    argocd-image-updater.argoproj.io/k8s-ai-react.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ai-react
  template:
    metadata:
      labels:
        app: k8s-ai-react
    spec:
      containers:
      - name: k8s-ai-react
        image: lkh8150/k8s-ai-react:latest  # 도커허브 이미지
        imagePullPolicy: Always
        ports:
        - containerPort: 80
