apiVersion: v1
kind: Service
metadata:
  name: k8s-ai-react
  namespace: react
spec:
  type: NodePort
  selector:
    app: k8s-ai-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30975

